language: ruby

rvm:
  - 2.1
  - 2.2.6
  - 2.3.3
  - 2.4

script: "bundle exec rake spec"

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/rails_5.0.gemfile
      rvm: 2.1

sudo: false
cache: bundler
